#!/usr/bin/env python3
"""
漏洞扫描看板 - GitHub 同步脚本
自动将生成的 HTML 推送到 GitHub 仓库
支持版本记录
"""

import json
import os
import subprocess
import sys
import time
from datetime import datetime
from pathlib import Path

# 配置
GITHUB_REPO = "https://github.com/yuyouquan/vuln-scan-dashboard"
GITHUB_USER = "yuyouquan"
REPO_NAME = "vuln-scan-dashboard"
LOCAL_REPO_PATH = "/tmp/vuln-dashboard-git"
HTML_SOURCE_DIR = "/tmp/vuln_dashboard_html"
HTML_INDEX_FILE = "index.html"

# Git 配置
GIT_AUTHOR_NAME = "Vuln Dashboard Bot"
GIT_AUTHOR_EMAIL = "bot@vuln-dashboard.local"

# 版本记录文件
VERSION_FILE = "versions.json"
CHANGELOG_FILE = "CHANGELOG.md"


def run_command(cmd, cwd=None, check=True):
    """执行 shell 命令"""
    try:
        result = subprocess.run(
            cmd,
            shell=True,
            cwd=cwd,
            capture_output=True,
            text=True
        )
        if check and result.returncode != 0:
            print(f"Command failed: {cmd}")
            print(f"Error: {result.stderr}")
            return None
        return result.stdout.strip()
    except Exception as e:
        print(f"Error running command: {e}")
        return None


def init_repo():
    """初始化 Git 仓库"""
    if os.path.exists(LOCAL_REPO_PATH):
        print(f"Repository already exists at {LOCAL_REPO_PATH}")
        return True
    
    # 尝试克隆现有仓库
    clone_url = f"https://github.com/{GITHUB_USER}/{REPO_NAME}.git"
    result = subprocess.run(
                ["git", "clone", clone_url, LOCAL_REPO_PATH],
                capture_output=True,
                text=True
            )
    
    if result.returncode != 0:
        # 仓库不存在，创建新仓库
        print("Repository does not exist, creating new one...")
        os.makedirs(LOCAL_REPO_PATH, exist_ok=True)
        run_command("git init", cwd=LOCAL_REPO_PATH)
        run_command(f"git config user.name '{GIT_AUTHOR_NAME}'", cwd=LOCAL_REPO_PATH)
        run_command(f"git config user.email '{GIT_AUTHOR_EMAIL}'", cwd=LOCAL_REPO_PATH)
        
        # 创建初始 README
        readme_content = f"""# {REPO_NAME}

Vulnerability Scan Dashboard

This dashboard displays the status of vulnerability scans using Strix, Nikto, and Nmap.

## Usage

1. Ensure scan data is available at `/tmp/vuln_dashboard_data.json`
2. Run the data collector: `python data_collector.py`
3. Run this sync script: `python sync_github.py`

## Features

- Real-time scan progress monitoring
- Multi-tool support (Strix, Nikto, Nmap)
- GitHub version history
- Automatic HTML generation

## Auto-generated by Vuln Dashboard
"""
        with open(os.path.join(LOCAL_REPO_PATH, "README.md"), 'w') as f:
            f.write(readme_content)
        
        # 初始提交
        run_command("git add README.md", cwd=LOCAL_REPO_PATH)
        run_command('git commit -m "Initial commit"', cwd=LOCAL_REPO_PATH)
        
        # 注意: 需要手动创建 GitHub 仓库并配置 remote
        print(f"Please create repository at {GITHUB_REPO} manually")
        return True
    
    # 配置 git
    run_command(f"git config user.name '{GIT_AUTHOR_NAME}'", cwd=LOCAL_REPO_PATH)
    run_command(f"git config user.email '{GIT_AUTHOR_EMAIL}'", cwd=LOCAL_REPO_PATH)
    
    return True


def load_html_content():
    """加载 HTML 内容"""
    html_path = os.path.join(HTML_SOURCE_DIR, HTML_INDEX_FILE)
    
    if not os.path.exists(html_path):
        # 尝试从 dashboard 数据生成简单 HTML
        dashboard_data_path = "/tmp/vuln_dashboard_data.json"
        if os.path.exists(dashboard_data_path):
            with open(dashboard_data_path, 'r') as f:
                data = json.load(f)
            return generate_simple_html(data)
        else:
            print(f"HTML file not found: {html_path}")
            return None
    
    with open(html_path, 'r', encoding='utf-8') as f:
        return f.read()


def generate_simple_html(data):
    """从 dashboard 数据生成简单的 HTML"""
    import json
    
    projects_html = ""
    for project in data.get("projects", []):
        targets_html = ""
        for target in project.get("targets", []):
            tools_html = ""
            for tool in target.get("tools", []):
                status_class = "status-pending"
                if tool.get("status") == "scanning":
                    status_class = "status-scanning"
                elif tool.get("status") == "completed":
                    status_class = "status-completed"
                
                tools_html += f"""
                <div class="tool-card">
                    <h4>{tool.get('name')}</h4>
                    <span class="status {status_class}">{tool.get('status')}</span>
                    <div class="progress-bar">
                        <div class="progress-fill" style="width: {tool.get('progress', 0)}%"></div>
                    </div>
                    <p>Progress: {tool.get('progress', 0)}%</p>
                    <p>Scanned: {tool.get('scanned', 0)}</p>
                    <p>Found: {tool.get('found', 0)}</p>
                </div>
                """
            
            targets_html += f"""
            <div class="target-card">
                <h3>{target.get('name')}</h3>
                <div class="tools-grid">
                    {tools_html}
                </div>
            </div>
            """
        
        proj_status_class = "status-pending"
        if project.get("status") == "scanning":
            proj_status_class = "status-scanning"
        elif project.get("status") == "completed":
            proj_status_class = "status-completed"
        
        projects_html += f"""
        <div class="project-card">
            <h2>{project.get('name')}</h2>
            <span class="status {proj_status_class}">{project.get('status')}</span>
            <div class="progress-bar">
                <div class="progress-fill" style="width: {project.get('progress', 0)}%"></div>
            </div>
            <div class="targets-container">
                {targets_html}
            </div>
        </div>
        """
    
    html = f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Vulnerability Scan Dashboard</title>
    <style>
        * {{ margin: 0; padding: 0; box-sizing: border-box; }}
        body {{ font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; background: #f5f5f5; padding: 20px; }}
        .container {{ max-width: 1200px; margin: 0 auto; }}
        h1 {{ text-align: center; margin-bottom: 30px; color: #333; }}
        .project-card {{ background: white; border-radius: 8px; padding: 20px; margin-bottom: 20px; box-shadow: 0 2px 4px rgba(0,0,0,0.1); }}
        .target-card {{ background: #f9f9f9; border-radius: 6px; padding: 15px; margin: 15px 0; }}
        .tools-grid {{ display: grid; grid-template-columns: repeat(auto-fit, minmax(200px, 1fr)); gap: 15px; }}
        .tool-card {{ background: white; border-radius: 4px; padding: 15px; border: 1px solid #eee; }}
        .tool-card h4 {{ margin-bottom: 10px; color: #555; }}
        .progress-bar {{ background: #e0e0e0; border-radius: 10px; height: 20px; overflow: hidden; margin: 10px 0; }}
        .progress-fill {{ background: linear-gradient(90deg, #4CAF50, #8BC34A); height: 100%; transition: width 0.3s; }}
        .status {{ display: inline-block; padding: 4px 12px; border-radius: 12px; font-size: 12px; font-weight: bold; text-transform: uppercase; }}
        .status-pending {{ background: #9e9e9e; color: white; }}
        .status-scanning {{ background: #2196F3; color: white; }}
        .status-completed {{ background: #4CAF50; color: white; }}
        .last-updated {{ text-align: center; color: #888; margin-top: 20px; font-size: 14px; }}
    </style>
</head>
<body>
    <div class="container">
        <h1>🔒 Vulnerability Scan Dashboard</h1>
        {projects_html}
        <p class="last-updated">Last Updated: {data.get('last_updated', 'N/A')}</p>
    </div>
</body>
</html>
"""
    return html


def load_version_history():
    """加载版本历史"""
    version_path = os.path.join(LOCAL_REPO_PATH, VERSION_FILE)
    
    if os.path.exists(version_path):
        with open(version_path, 'r') as f:
            return json.load(f)
    
    return {"versions": []}


def save_version_history(history):
    """保存版本历史"""
    version_path = os.path.join(LOCAL_REPO_PATH, VERSION_FILE)
    with open(version_path, 'w') as f:
        json.dump(history, f, indent=2)


def generate_version_tag():
    """生成版本标签"""
    return datetime.now().strftime("v%Y%m%d-%H%M%S")


def update_changelog(history):
    """更新 CHANGELOG"""
    changelog_path = os.path.join(LOCAL_REPO_PATH, CHANGELOG_FILE)
    
    latest = history["versions"][0] if history["versions"] else {}
    version = latest.get("version", "v1.0.0")
    date = latest.get("timestamp", datetime.now().isoformat())
    
    changelog_content = f"""# Changelog

## [{version}] - {date}

### Added
- Dashboard HTML export
- Version tracking

---

*Auto-generated by Vuln Dashboard*
"""
    
    with open(changelog_path, 'w') as f:
        f.write(changelog_content)


def sync_to_github(commit_message=None):
    """同步到 GitHub"""
    print("Starting GitHub sync...")
    
    # 初始化仓库
    if not init_repo():
        print("Failed to initialize repository")
        return False
    
    # 加载 HTML 内容
    html_content = load_html_content()
    if not html_content:
        print("No HTML content to sync")
        return False
    
    # 写入 HTML 文件
    html_path = os.path.join(LOCAL_REPO_PATH, HTML_INDEX_FILE)
    with open(html_path, 'w', encoding='utf-8') as f:
        f.write(html_content)
    
    print(f"HTML written to {html_path}")
    
    # 加载并更新版本历史
    history = load_version_history()
    
    # 生成新版本
    new_version = generate_version_tag()
    version_entry = {
        "version": new_version,
        "timestamp": datetime.now().isoformat(),
        "message": commit_message or f"Update dashboard - {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}",
        "projects_count": len(json.loads(html_content).get("projects", []))
    }
    
    # 添加到历史（保留最近 50 个版本）
    history["versions"].insert(0, version_entry)
    history["versions"] = history["versions"][:50]
    
    save_version_history(history)
    update_changelog(history)
    
    # Git 操作
    run_command("git add .", cwd=LOCAL_REPO_PATH)
    
    # 检查是否有更改
    status = run_command("git status --porcelain", cwd=LOCAL_REPO_PATH)
    if not status:
        print("No changes to commit")
        return True
    
    # 提交
    commit_msg = commit_message or f"Update dashboard - {new_version}"
    run_command(f'git commit -m "{commit_msg}"', cwd=LOCAL_REPO_PATH)
    
    # 尝试推送到 GitHub
    # 注意: 需要配置 GitHub token 或 SSH 密钥
    push_result = run_command("git push origin main", cwd=LOCAL_REPO_PATH, check=False)
    
    if push_result is None:
        # 可能是 main 分支不存在，尝试 master
        push_result = run_command("git push origin master", cwd=LOCAL_REPO_PATH, check=False)
    
    if push_result is None:
        print("Warning: Failed to push to GitHub")
        print("Changes committed locally. Push manually with:")
        print(f"  cd {LOCAL_REPO_PATH}")
        print("  git push origin main")
        return False
    
    print(f"Successfully synced to GitHub: {GITHUB_REPO}")
    print(f"Version: {new_version}")
    
    return True


def show_version_history():
    """显示版本历史"""
    history = load_version_history()
    
    print("\n=== Version History ===")
    for v in history["versions"][:10]:
        print(f"{v['version']} - {v['timestamp']}")
        print(f"  {v['message']}")
        print()


def main():
    """主函数"""
    import argparse
    
    parser = argparse.ArgumentParser(description="Sync dashboard to GitHub")
    parser.add_argument("-m", "--message", help="Commit message")
    parser.add_argument("--history", action="store_true", help="Show version history")
    parser.add_argument("--init", action="store_true", help="Initialize repository")
    
    args = parser.parse_args()
    
    if args.history:
        show_version_history()
        return
    
    if args.init:
        init_repo()
        return
    
    # 执行同步
    success = sync_to_github(args.message)
    sys.exit(0 if success else 1)


if __name__ == "__main__":
    main()
